dns_addresses:
- 9.9.9.9
- 149.112.112.112
- 1.1.1.1
- 1.0.0.1
run_on_startup: false
change_interval_hours: 6
notify_user: true
test_domains:
- google.com
- cloudflare.com
- github.com
- microsoft.com
- amazon.com
